#if !defined(VKSTATS_CONFIG_H)
#define VKSTATS_CONFIG_H

#define MAX_INSTANCE_LAYER_PROPERTIES 13
#define MAX_PHYSICAL_DEVICES 2
#define MAX_QUEUE_FAMILIES 10
#define MAX_QUEUES 2
#define MAX_POOLS MAX_QUEUES

#endif
